# H2 CONFIGS
spring.datasource.url=jdbc:h2:mem:catalogdb
spring.h2.console.enabled=true
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



# LOG
logging.level.com.phtdev.webshopcatalog.service=INFO

# REDIS
spring.data.redis.host=localhost
spring.data.redis.port=6379

app.cache.name=categories
app.cache.ttl-hours=24